apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: online-inference-replicaset
  labels:
    app: online-inference
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: online-inference
  template:
    metadata:
      labels:
        app: online-inference
    spec:
      containers:
        - name: online-inference-replicaset
          image: ruslan16/ml_in_prod_2022:v1
          ports:
            -  containerPort: 8080
