apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-inference-deployment
  labels:
    app: online-inference
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  selector:
    matchLabels: 
      app: online-inference
  template:
    metadata:
      labels:
        app: online-inference
    spec:
      containers:
        - name: online-inference-deployment
          image: ruslan16/ml_in_prod_2022:v1
          ports:
            -  containerPort: 8080
