hydra:
  run:
    dir: "configs"
defaults:
    - _self_
    - models: "busting"
    - override hydra/job_logging: custom
metrics_path: "../reports/report.json"
output_model_path: "../artifacts/model.pkl"
downloading_params:
  url: "https://raw.githubusercontent.com/ruslan16bmstu/ML/main/heart_cleveland_upload.csv"
  filename: "heart_cleveland_upload.csv"
  output_folder: "../ml_project/raw"
splitting_params:
  val_size: 0.2
  random_state: 42
train_params:
  model_type: "LogisticRegression"
feature_params:
  default_features:
    - "sex"
    - "fbs"
    - "exang"
  float_features:
    - "age"
    - "trestbps"
    - "chol"
    - "restecg"
    - "oldpeak"
  integer_features:
    - "cp"
    - "slope"
    - "ca"
    - "thal"
  target_col: "condition"
