hydra:
  run:
    dir: .
defaults:
    - _self_
    - model: logreg
    - override hydra/job_logging: custom
metrics_path: reports/report.json
output_model_path: artifacts/model.pkl
downloading_params:
  url: https://raw.githubusercontent.com/ruslan16bmstu/ML/main/heart_cleveland_upload.csv
  file_path: raw/heart_cleveland_upload.csv
splitting_params:
  val_size: 0.2
  random_state: 42
feature_params:
  default_features:
    - sex
    - fbs
    - exang
  float_features:
    - age
    - trestbps
    - chol
    - restecg
    - oldpeak
  integer_features:
    - cp
    - slope
    - ca
    - thal
  target_col: condition
